version: '3.3'
services:
 php:
  image: php:8.2.10-apache
  volumes:
    - ./:/var/www/html
  expose:
    - 80
  ports:
    - 80:80
  command: 
    - bash
    - -c 
    -  
      chmod +x script.sh &&  
      ./script.sh